# Generated by Django 4.1.6 on 2023-03-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_decision', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.process')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
