# Generated by Django 4.1.6 on 2023-03-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiots', '0001_initial'),
        ('workflow_engine', '0001_initial'),
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rvat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, null=True)),
                ('rvat_au_regional', models.BooleanField(default=False)),
                ('verifie', models.BooleanField(default=False)),
                ('date_limite_verification', models.DateField(null=True)),
                ('commentaire_verificateur', models.TextField(null=True)),
                ('approuve', models.BooleanField(default=False)),
                ('date_limite_approbation', models.DateField(null=True)),
                ('commentaire_approbateur', models.TextField()),
                ('approuve_regional', models.BooleanField(default=False)),
                ('date_limite_approbation_regional', models.DateField(null=True)),
                ('commentaire_regional', models.TextField()),
                ('uri_travail', models.CharField(max_length=255)),
                ('uri_travail_regional', models.CharField(max_length=255)),
                ('uri_definitif', models.CharField(max_length=255)),
                ('reference_regional', models.CharField(max_length=255, null=True)),
                ('reference', models.CharField(max_length=255)),
                ('administratif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvats_administres', to='auth.group')),
                ('aiot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvats', to='aiots.aiot')),
                ('approbateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvats_approuves', to='auth.group')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.process')),
                ('redacteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvats', to=settings.AUTH_USER_MODEL)),
                ('verificateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rvats_verifies', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
