# Generated by Django 4.1.6 on 2023-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rvat',
            name='commentaire_approbateur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rvat',
            name='commentaire_regional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
