# Generated by Django 4.1.6 on 2023-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvat',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
