# Generated by Django 4.1.6 on 2023-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_rvat_commentaire_approbateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rvat',
            name='transmis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rvat',
            name='transmis_le',
            field=models.DateField(null=True),
        ),
    ]
