# Generated by Django 4.1.6 on 2023-02-21 13:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RubriqueIcpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('regime', models.CharField(choices=[('A', 'Autorisation'), ('E', 'Enregistrement'), ('DC', 'Déclaration avec contrôle périodique'), ('D', 'Déclaration'), ('NC', 'Non-classé')], default='NC', max_length=2)),
                ('libelle', models.TextField()),
                ('description', models.TextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aiots.rubriqueicpe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatutAiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RubriqueIcpeAiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_autorisation', models.DateField(null=True)),
                ('date_entree_en_vigueur', models.DateField(null=True)),
                ('date_cessation', models.DateField(null=True)),
                ('aiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_icpe', to='aiots.aiot')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiots.rubriqueicpe')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('code', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiots.region')),
            ],
            options={
                'unique_together': {('code', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('abbv', models.CharField(max_length=10)),
                ('code_insee', models.CharField(max_length=10, null=True)),
                ('code_postal', models.CharField(max_length=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiots.departement')),
            ],
            options={
                'unique_together': {('code_postal', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='aiot',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiots.commune'),
        ),
        migrations.AddField(
            model_name='aiot',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiots.statutaiot'),
        ),
        migrations.AlterUniqueTogether(
            name='aiot',
            unique_together={('code',)},
        ),
    ]
