# Generated by Django 4.1.6 on 2023-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiot',
            name='a_poi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiot',
            name='adresse_site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiot',
            name='complement_adresse_site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiot',
            name='courriel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiot',
            name='date_poi',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='aiot',
            name='ied',
            field=models.BooleanField(default=False),
        ),
    ]
