# Generated by Django 4.1.6 on 2023-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
