# Generated by Django 4.1.6 on 2023-03-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiots', '0002_alter_departement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='abbv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code_insee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code_postal',
            field=models.CharField(max_length=50),
        ),
    ]
