# Generated by Django 4.1.6 on 2023-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviinspection',
            name='date_inspection',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suiviinspection',
            name='date_preparation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suiviinspection',
            name='date_previsionnelle',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suiviinspection',
            name='date_publication',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='suiviinspection',
            name='date_rapport',
            field=models.DateTimeField(null=True),
        ),
    ]
