# Generated by Django 4.1.6 on 2023-02-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivis', '0002_suiviinspection_date_inspection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basesuivi',
            old_name='status',
            new_name='statut',
        ),
    ]
