# Generated by Django 4.1.6 on 2023-03-02 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_class', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initialised'), ('running', 'Running'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done')], default='init', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initalised'), ('ready', 'Ready'), ('stall', 'Stall'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done'), ('closed', 'Closed')], default='init', max_length=20)),
                ('log', models.TextField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.process')),
            ],
        ),
    ]
