# Generated by Django 4.1.6 on 2023-03-03 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0015_group_level_group_lft_group_parent_group_rght_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_class', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initialised'), ('running', 'Running'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done')], default='init', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initalised'), ('ready', 'Ready'), ('stall', 'Stall'), ('submitted', 'Submitted'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done'), ('closed', 'Closed')], default='init', max_length=20)),
                ('current_job', models.CharField(max_length=255, null=True)),
                ('log', models.TextField()),
                ('assigned_to_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('assigned_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followings', to='workflow_engine.task')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow_engine.process')),
                ('subprocess', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supratasks', to='workflow_engine.process')),
            ],
        ),
    ]
