# Generated by Django 4.1.6 on 2023-03-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_class', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initialised'), ('running', 'Running'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('init', 'Initalised'), ('ready', 'Ready'), ('idling', 'Idling'), ('aborted', 'Aborted'), ('failed', 'Failed'), ('done', 'Done'), ('closed', 'Closed')], max_length=20)),
                ('log', models.TextField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.process')),
            ],
        ),
    ]
