# Generated by Django 4.1.6 on 2023-03-08 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
