# Generated by Django 4.1.6 on 2023-03-10 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow_engine', '0002_task_done_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='closed_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='closed_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
