# Generated by Django 4.1.6 on 2023-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0003_process_closed_at_process_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
