# Generated by Django 4.1.6 on 2023-02-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import ems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('aiot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.aiot')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TrackerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerInspection',
            fields=[
                ('tracker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ems.tracker')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ems.tracker',),
        ),
        migrations.CreateModel(
            name='TrackerInstruction',
            fields=[
                ('tracker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ems.tracker')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('ems.tracker',),
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.trackerstatus'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('obj', models.FileField(upload_to=ems.models.object_directory_path)),
                ('oname', models.CharField(max_length=255)),
                ('oid', models.CharField(max_length=1024)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.document')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.region')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('abbv', models.CharField(max_length=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.departement')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('aiot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.aiot')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ems.cabinetnode', verbose_name='parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aiot',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ems.commune'),
        ),
    ]
